services:
  beetroot:
    image: ${BEETROOT_IMAGE}
    env_file:
      - ../beetroot/.env
    volumes:
      - ../beetroot/content.txt:/app/content.txt:ro
    expose:
      - "8080"

  reverse_proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - beetroot
